### ISSUE TITLE
visual_behavior module missing

### ISSUE THREAD

**Issue by RobertoDF** [alexpiet/licking_behavior#376]
HI,

These imports here fail https://github.com/alexpiet/licking_behavior/blob/feb9158997e60ffef44f70354b62ff1fc6813764/src/psy_general_tools.py#L4-L5

I could figure out the library is this one [here](https://github.com/AllenInstitute/visual_behavior_analysis). 
Though it´s not trivial to install it because there are some incompatibilities with the env created using the yml file.

**Comment by alexpiet** [comment]
Yes, my code is tied to a specific commit, because that package kept changing (see this comment in the environment.yml file):

```
# allensdk 2.13.4, Git commit: 351850c7
# VBA 0.13.1, but meaningless. Git commit: a0b0ce5e
```

**Comment by RobertoDF** [comment]
ok, great didn´t notice that acronym VBA.
